apiVersion: "bsctl.dev/v1alpha1"
kind: "CommunityBuilder"
metadata:
    labels: {}
    name: PlatformCommunity
definition:
    name: Platform Engineer
    criterion:
        - They are working on an internal developer platform
        - They describe their job role as platform engineer, ml platform engineer, devops, infrastructure engineer or SRE
        - They work with technologies used to build platforms; eg. kubernetes, cloud, argo
        - They describe practices central to platform engineering; e.g. IAC, configuration, containers, gitops, cicd
    examples:
        - profile: I'm a platform engineer at acme.co
          member: true
          explanation: ""
seeds:
    - handle: jeremy.lewi.us
      did: ""
outputFile: /Users/jlewi/git_bskylists/jeremylewi.followers.platformengineering.yaml
